print("Decimal To Square Meter To Square Feet converter")
print("1.Decimal to Square Meters")
print("2.Decimal to Square Feet")
choise = float(input('Your Choise?'))
if choise == 1:
 x = float(input("Please input Decimal:"))
 print("You have entered", x, "Decimal.")
 print("Converting it to Square Meters.")
 y = x*float(40.5)
 print(x, "Decimal is equal to", y, "Square Meters.")
if choise == 2:
 x = float(input("Please input Decimal:"))
 print("You have entered", x, "Decimal.")
 print("Converting it to Square Feet.")
 z = x*float(435.6)
 print(x, "Decimal is equal to", z, "Square Feet.")
