print("Decimal To Square Meter To Square Feet converter")
x = float(input("Please input Decimal:"))
print("You have entered", x, "Decimal.")
print("Converting it to Square Meters.")
y = x*float(40.5)
print(x, "Decimal is equal to", y, "Square Meters.")
z = x*float(435.6)
print(x, "Decimal is equal to", z, "Square Feet.")
print("Thank you..............")
